# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 639)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.api_token_label = QtWidgets.QLabel(parent=self.tab)
        self.api_token_label.setText("")
        self.api_token_label.setPixmap(QtGui.QPixmap("Assets/Labels/API_token_label.png"))
        self.api_token_label.setObjectName("api_token_label")
        self.horizontalLayout.addWidget(self.api_token_label)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/Buttons/input_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.run_bot_button = QtWidgets.QPushButton(parent=self.tab)
        self.run_bot_button.setMaximumSize(QtCore.QSize(55, 70))
        self.run_bot_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/Buttons/run_bot_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.run_bot_button.setIcon(icon1)
        self.run_bot_button.setIconSize(QtCore.QSize(100, 100))
        self.run_bot_button.setFlat(True)
        self.run_bot_button.setObjectName("run_bot_button")
        self.verticalLayout.addWidget(self.run_bot_button)
        self.pause_button = QtWidgets.QPushButton(parent=self.tab)
        self.pause_button.setMaximumSize(QtCore.QSize(55, 70))
        self.pause_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/Buttons/pause_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pause_button.setIcon(icon2)
        self.pause_button.setIconSize(QtCore.QSize(100, 100))
        self.pause_button.setFlat(True)
        self.pause_button.setObjectName("pause_button")
        self.verticalLayout.addWidget(self.pause_button)
        self.line_label = QtWidgets.QLabel(parent=self.tab)
        self.line_label.setMaximumSize(QtCore.QSize(70, 5))
        self.line_label.setText("")
        self.line_label.setPixmap(QtGui.QPixmap("Assets/BG/line.png"))
        self.line_label.setObjectName("line_label")
        self.verticalLayout.addWidget(self.line_label)
        self.plus_button = QtWidgets.QPushButton(parent=self.tab)
        self.plus_button.setMaximumSize(QtCore.QSize(55, 70))
        self.plus_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/Buttons/plus_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.plus_button.setIcon(icon3)
        self.plus_button.setIconSize(QtCore.QSize(100, 100))
        self.plus_button.setFlat(True)
        self.plus_button.setObjectName("plus_button")
        self.verticalLayout.addWidget(self.plus_button)
        self.undo_button = QtWidgets.QPushButton(parent=self.tab)
        self.undo_button.setMaximumSize(QtCore.QSize(50, 70))
        self.undo_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/Buttons/undo_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.undo_button.setIcon(icon4)
        self.undo_button.setIconSize(QtCore.QSize(100, 100))
        self.undo_button.setFlat(True)
        self.undo_button.setObjectName("undo_button")
        self.verticalLayout.addWidget(self.undo_button)
        self.plus_button_3 = QtWidgets.QPushButton(parent=self.tab)
        self.plus_button_3.setMaximumSize(QtCore.QSize(50, 70))
        self.plus_button_3.setText("")
        self.plus_button_3.setIcon(icon3)
        self.plus_button_3.setIconSize(QtCore.QSize(100, 100))
        self.plus_button_3.setFlat(True)
        self.plus_button_3.setObjectName("plus_button_3")
        self.verticalLayout.addWidget(self.plus_button_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 3, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(213, 213, 213);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(100, 57, 255, 150), stop:0.991071 rgba(79, 117, 255, 150));\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(100, 57, 255, 200), stop:0.991071 rgba(79, 117, 255, 200));\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(100, 57, 255, 255), stop:0.991071 rgba(79, 117, 255, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(213, 213, 213);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color:rgb(213, 213, 213);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color:  rgb(235, 235, 235);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(213, 213, 213);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(213, 213, 213);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 918, 724))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_4)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 350))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 350))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
