# Form implementation generated from reading ui file 'Designer.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 639)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    background: white;\n"
"    border:5px white;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color:rgba(255, 255, 255, 0) ;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding:3px;\n"
"\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(102, 88, 255);\n"
"}\n"
"QTabBar::tab:!selected:hover {\n"
"    background: rgb(135, 156, 238);\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setStyleSheet("font: 63 55pt \"Oceanwide QLt\";\n"
"color:rgb(13, 9, 39);\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton = QtWidgets.QToolButton(parent=self.groupBox_2)
        self.toolButton.setStyleSheet("QToolButton{\n"
"    border-radius: 10px;\n"
"    height: 30px;\n"
"    width: 50px;\n"
"    background-color: rgb(162, 82, 251);\n"
"}")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    height: 30px;\n"
"    background-color: rgb(115, 114, 243);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    height: 30px;\n"
"    background-color:rgb(64, 149, 233);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox.setMinimumSize(QtCore.QSize(104, 40))
        self.comboBox.setStyleSheet("QComboBox {\n"
"border: 0px;\n"
"border-radius: 5px;\n"
"background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(79, 117, 255, 255), stop:0.0113636 rgba(182, 68, 255, 255), stop:1 rgba(0, 193, 221, 255));\n"
"padding: 1px 23px 1px 3px;\n"
"min-width: 6em;\n"
"\n"
"}\n"
"QComboBox QAbstractItemView {background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(79, 117, 255, 255), stop:0.0113636 rgba(182, 68, 255, 255), stop:1 rgba(0, 193, 221, 255));}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setStyleSheet("font: 63 25pt \"Oceanwide QLt\";\n"
"color:rgb(54, 54, 54);\n"
"")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/Buttons/input_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.run_bot_button = QtWidgets.QPushButton(parent=self.tab)
        self.run_bot_button.setMaximumSize(QtCore.QSize(55, 70))
        self.run_bot_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/Buttons/run_bot_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.run_bot_button.setIcon(icon1)
        self.run_bot_button.setIconSize(QtCore.QSize(100, 100))
        self.run_bot_button.setFlat(True)
        self.run_bot_button.setObjectName("run_bot_button")
        self.verticalLayout.addWidget(self.run_bot_button)
        self.pause_button = QtWidgets.QPushButton(parent=self.tab)
        self.pause_button.setMaximumSize(QtCore.QSize(55, 70))
        self.pause_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/Buttons/pause_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pause_button.setIcon(icon2)
        self.pause_button.setIconSize(QtCore.QSize(100, 100))
        self.pause_button.setFlat(True)
        self.pause_button.setObjectName("pause_button")
        self.verticalLayout.addWidget(self.pause_button)
        self.line_label = QtWidgets.QLabel(parent=self.tab)
        self.line_label.setMaximumSize(QtCore.QSize(70, 5))
        self.line_label.setText("")
        self.line_label.setPixmap(QtGui.QPixmap("Assets/BG/line.png"))
        self.line_label.setObjectName("line_label")
        self.verticalLayout.addWidget(self.line_label)
        self.plus_button = QtWidgets.QPushButton(parent=self.tab)
        self.plus_button.setMaximumSize(QtCore.QSize(55, 70))
        self.plus_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/Buttons/plus_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.plus_button.setIcon(icon3)
        self.plus_button.setIconSize(QtCore.QSize(100, 100))
        self.plus_button.setFlat(True)
        self.plus_button.setObjectName("plus_button")
        self.verticalLayout.addWidget(self.plus_button)
        self.undo_button = QtWidgets.QPushButton(parent=self.tab)
        self.undo_button.setMaximumSize(QtCore.QSize(50, 70))
        self.undo_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/Buttons/undo_button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.undo_button.setIcon(icon4)
        self.undo_button.setIconSize(QtCore.QSize(100, 100))
        self.undo_button.setFlat(True)
        self.undo_button.setObjectName("undo_button")
        self.verticalLayout.addWidget(self.undo_button)
        self.plus_button_3 = QtWidgets.QPushButton(parent=self.tab)
        self.plus_button_3.setMaximumSize(QtCore.QSize(50, 70))
        self.plus_button_3.setText("")
        self.plus_button_3.setIcon(icon3)
        self.plus_button_3.setIconSize(QtCore.QSize(100, 100))
        self.plus_button_3.setFlat(True)
        self.plus_button_3.setObjectName("plus_button_3")
        self.verticalLayout.addWidget(self.plus_button_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 3, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.tab)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    border: 10px;\n"
"    border-radius: 7px;\n"
"    }\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(213, 213, 213);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(100, 57, 255, 150), stop:0.991071 rgba(79, 117, 255, 150));\n"
"    min-height: 10px;\n"
"    max-height: 10px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(100, 57, 255, 200), stop:0.991071 rgba(79, 117, 255, 200));\n"
"\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(100, 57, 255, 255), stop:0.991071 rgba(79, 117, 255, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(213, 213, 213);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(213, 213, 213);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:  rgb(235, 235, 235);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(213, 213, 213);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"    background-color: rgb(213, 213, 213);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 926, 532))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcome_message_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_message_button.sizePolicy().hasHeightForWidth())
        self.welcome_message_button.setSizePolicy(sizePolicy)
        self.welcome_message_button.setMinimumSize(QtCore.QSize(500, 120))
        self.welcome_message_button.setStyleSheet("QPushButton{\n"
"    border-radius: 40px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(96, 86, 255, 255), stop:1 rgba(179, 146, 221, 255));\n"
"    font: 63 56pt \"Oceanwide QLt\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.welcome_message_button.setObjectName("welcome_message_button")
        self.verticalLayout_2.addWidget(self.welcome_message_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "Welcome......"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Bot 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bot 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label_3.setText(_translate("MainWindow", "API token:"))
        self.welcome_message_button.setText(_translate("MainWindow", "/welcome Message"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
